### ISSUE TITLE
Add CT tests for public query parameters

### ISSUE THREAD

**Issue by zepumph** [phetsims/aqua#105]
Since public query parameters are available to the public, it would be nice if we were testing them on CT. I think the basic thing to do is to pick one single screen sim, and one multi-screen sim, and run it with correct and incorrect parameters. When `?ea` is not provided, the sim should not error given wrong `public` parameters.

**Comment by zepumph** [comment]
This idea comes from my mistake in https://github.com/phetsims/joist/issues/641#issuecomment-668865380

**Comment by zepumph** [comment]
@jonathanolson, does this seem reasonable to you? Feel free to close.

**Comment by pixelzoom** [comment]
There's been no progress on this issue, and what @zepumph did seems reasonable to me.  Assigning to @ariel-phet to decide how to proceed.

**Comment by ariel-phet** [comment]
That seems to be enough people feeling it is reasonable to me, closing

**Comment by samreid** [comment]
In slack, someone pointed out:

> Yep. Failing with “Uncaught Error: Assertion failed: Cannot add the same listener twice”

Sam Reid  9:38 AM
Perhaps we should change it to ?screens=1,2.  Why did it just start failing recently?  Also, what is supposed to happen if you specify ?screens=1,2 on a one-screen sim?

Chris Malley  9:39 AM
Re code dependencies on git, I don’t know, not in my wheelhouse…. Let’s tell the user to check his repo into GitHub as a workaround (so he can hopefully proceed), and discuss at dev meeting?

Jonathan Olson  9:39 AM
It looks like a test specifically testing the "verbose" form of it. And it only runs on acid-base-solutions
9:39
I'm investigating a quick solution, I'll push back if I don't find one

Chris Malley  9:39 AM
screensVerbose does not look at all appropriate to include in commonQueryParameters.
9:42
Let’s hear from @mjkauzmann about why it’s there, and what’s supposed to happen for 1-screen sims.  And we should think about fixing the error message, because “Cannot add the same listener twice”.  screens is a {number[]} so should be failing with a more general, comprehensible error message in this case.
9:42
I’m not working today… Can someone capture this stuff about screensVerbose is a general issue?

Sam Reid  9:43 AM
I’ll reopen https://github.com/phetsims/aqua/issues/105 and comment there
New

Chris Malley  9:44 AM
Those commits that we’ve identified are not new. So I’m also curious about what changed that suddenly made this fail CT.

**Comment by samreid** [comment]
@pixelzoom added:

> … and why those changes apparently weren’t tested before being pushed.  CT lit up like a Christmas Tree starting at 10:45pm last night.

**Comment by zepumph** [comment]
I do not think this is the "general" issue you are looking for to solve the CT error, "cannot add the same listener twice."  This error is more systemic, and is showing up also in https://github.com/phetsims/projectile-motion/issues/255 and others. 

This issue was created to test public query parameters, which are DESIGNED to accept faulty values and not fail. That is why you get incorrect values in `commonQueryParameters` values. I'm going to close this issue.
