### ISSUE TITLE
Command to tell CT to give up on current snapshot, and pull all and start another

### ISSUE THREAD

**Issue by zepumph** [phetsims/aqua#116]
Sometimes CT shows a row very red because it grabbed a snapshot halfway through many repos getting committed and pushed. @jonathanolson could you comment on how easy it may be to add runtime control to CT so that it could be told to give up on a snapshot, and move on? I don' think this is high priority, but if it was simple enough, I may add it to my back burner.

**Comment by jonathanolson** [comment]
It would presumably be adding in an API that would allow removing a snapshot. Probably slightly complicated, especially if it's recent, since we'd still be getting testing results in for the next few minutes.

> halfway through many repos getting committed and pushed

There's usually quite a delay, is it possible to push all repos generally near the same time? It's not just a CT thing, if someone pulls at that time, it could be an issue.

**Comment by zepumph** [comment]
Yes agreed. Push delay is less than ideal. Webstorm is the cause for the long time when committing in 100 repos at a time. I could likely improve my pattern to just commit with Webstorm, and then use the command line to push all. Closing
