### ISSUE TITLE
Scenery unit tests are not running on CT

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/aqua#138]
I noticed that the scenery unit tests are not running on CT
![image](https://user-images.githubusercontent.com/6396244/162769646-a51890d3-347e-4209-a465-c3f73995d51c.png)

**Comment by jessegreenberg** [comment]
`scenery` is listed in perennial/data/unit-tests. Is it because there is no priority for unit tests here?

https://github.com/phetsims/perennial/blob/master/js/listContinuousTests.js#L267-L271

**Comment by jessegreenberg** [comment]
The accessibility tests take many seconds to run because of timeouts that are part of the testing. Maybe there is a timeout in CT that just moves on to the next test before any of the unit tests can provide a success/failure message.

**Comment by jessegreenberg** [comment]
They started showing up!
![image](https://user-images.githubusercontent.com/6396244/162826485-c61d7929-970b-4b95-973c-669fee5ade76.png)

**Comment by jessegreenberg** [comment]
We had scenery unit tests running for 10 consecutive columns last night so I am going to close this.

**Comment by zepumph** [comment]
To summarize this though, we don't know why failing unit tests were causing a lack of reporting here. It seems to have been fixed by the fixes in https://github.com/phetsims/scenery/commit/603005a048fad01ce9c6cf7e591ba4528040cc56 and https://github.com/phetsims/scenery/commit/be5ff55faae2406f758f85fd36722e7cbd59a324 over in https://github.com/phetsims/phet-io/issues/1847. I agree it isn't worth investigating further.
