### ISSUE TITLE
CT Lint failed status code 1

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/aqua#157]
```
aqua : lint
Lint failed with status code 1:
[4mRunning "lint" task[24m

/data/share/phet/continuous-testing/ct-snapshots/1660573705193/aqua/js/patient-snapshotter.ts
57:1 error Missing return type explicit-method-return-type
61:1 error Missing return type explicit-method-return-type
88:1 error Missing return type explicit-method-return-type
110:1 error Missing return type explicit-method-return-type
116:1 error Missing return type explicit-method-return-type
124:1 error Missing return type explicit-method-return-type

✖ 6 problems (6 errors, 0 warnings)
5 errors and 0 warnings potentially fixable with the `--fix` option.

[31mFatal error: Lint failed[39m

(node:22627) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Snapshot from 8/15/2022, 8:28:25 AM
```

**Comment by zepumph** [comment]
Aqua doesn't pull itself, so this fix requires a manual pull on bayes. I'm going to bring this up in dev meeting to see if it is ok to change this.

**Comment by jonathanolson** [comment]
Original reasoning was twofold for why aqua doesn't pull itself:

1. Running processes might become incompatible with HTML/JS run by clients (since the HTML/JS would be updated, but the running process wouldn't be unless it is restarted).
2. Some of aqua (the continuous report part in particular) is built, and gets checked in.

@zepumph thoughts on that?

**Comment by zepumph** [comment]
Makes a lot of sense to me. Here is the use case I am trying to solve for:

* Someone not me or you changes a lint rule
* They fix changes in aqua
* They test locally and all is passing
* They push and CTQ fails lint/typechecking
* An automated testing issue gets assigned to me because I'm the responsible dev of aqua. 
* I go onto aqua and pull all to fix the errors, never really guaranteed that I'm not pulling breaking code related to the above issues.

One solution is to know that master is live, and get used to developing on branches for aqua if it will break things. We could run test services from a production branch, and keep master unstable, but this will likely mean I'm just merging master into the production branch with the same potential for breakage, but more overhead. We can also try to remedy failing CTQ another way.

**Comment by jonathanolson** [comment]
That makes me lean toward keeping aqua up-to-date on CT. Changes to the interface (if necessary) can be done on a branch. Sound good?

**Comment by zepumph** [comment]
I like it! That would be really nice. I'll add it to my list.

**Comment by zepumph** [comment]
Actually, I"ll do it on https://github.com/phetsims/aqua/issues/165
