### ISSUE TITLE
CTQ status is not reliably reported to Slack#continouous-testing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#166]
CTQ is not showing up reliably in this Slack channel. For example, looking at the CT page, number-suite-common has been failing lint since 3/3/2023 2:52:40 PM (see below) and as of 3/5/2023 8:48 AM is not showing up in Slack#continouous-testing.

If there are multiple CTQ errors, is something considering them all fixes when only 1 of them has been fixed? 

Assigning to @zepumph @jonathanolson to investigate, @kathy-phet to prioritize.

<img width="894" alt="screenshot_2348" src="https://user-images.githubusercontent.com/3046552/222971382-4b22b424-0281-4f86-9c51-4924bb413ad2.png">

**Comment by pixelzoom** [comment]
In Slack#continouous-testing, @kathy-phet said:

> @chrisklus - can you please take a quick look at the above on Monday and comment on possible issues, I believe you were leading the work to consolidate the slack messaging piece of CT a while back. But let me know if I’m mistaken there.

**Comment by pixelzoom** [comment]
This bit us again today. Buggy code was checked in to the new 'community' repo.  It's failing lint in CTQ, reported on the CT webpage, not reported in Slack#continuous-testing.  Once again, I was the lucky dev to first encounter the problem, and I'm off on a tangent again instead of accomplishing what I wanted to accomplish.

Raising priority to top, because PhET depends heavily on CT and CTQ.  And assigning to @kathy-phet to prioritize.

**Comment by chrisklus** [comment]
@zepumph and I are planning to investigate this afternoon.

**Comment by zepumph** [comment]
@chrisklus and I spent an hour on this just now and only barely got to a point where we could iterate and understand the code effectively. We made many improvements along the way and if this issue should remain a priority. It should not try to be worked into the cracks of this iteration, but should have real time devoted to it (and I'd be very happy to get to work on it!).

We will check back in tomorrow.

**Comment by zepumph** [comment]
Today @chrisklus and I overhauled the quick server to get it ready for parsing these messages better. We have a few leads on where the problems are coming from, but our best guess is that we change the lint output so that it has individual repos as they run, and then an "all results" section. We should just parse that part for CTQ.

**Comment by zepumph** [comment]
I was able to find and fix a fair number of bugs about the lint error parsing, now I'm going to move on to tsc checking which is (on my machine at least) reporting errors like `tsc:   `. (blank).  Fun!

**Comment by zepumph** [comment]
I made good progress. With the help of @marlitas and @samreid the tsc command is not much easier to parse and report on. I pushed these new changes to sparky ctq. We will see if there is any trouble before too long.

**Comment by zepumph** [comment]
- [ ] As part of this issue I'd like to look into reportErrorStatus, documenting and updating if needed (but mostly trying to understand it).

**Comment by zepumph** [comment]
Ok. I have completed the work I see for this issue. All changes above are now pushed to production on sparky's `ct-quick` process. From here I think it would be best for @chrisklus to do the review.

@pixelzoom, please let us know if you run into any more trouble.

**Comment by chrisklus** [comment]
@zepumph and I did much of this review together to get me oriented and then I did some testing on my side and a bit more code review. Things are looking great! I tested all of the cases I could think of, including throwing an Error in code which @zepumph mentioned he had not tried out. It didn't always show up but I think that was just because sometimes the sim doesn't start up for the allotted time in the test case.

@zepumph and I ran into one issue where i didn't have an npm module and so an unexpected lint error triggered an assertion which was a failure farther downstream than we were expecting. I looked into this a little bit and found that the error was not sending an `stderr`, but I'm not sure why.

The only thing I noticed behavior wise was that a fuzz error reports as new error every loop. I think this may be because the server port is different every time? So it doesn't recognize it as the same error. But, it's good that it's not continuously adding to the number of errors every time, so that when it is fixed, there aren't a bunch of reported pre-existing errors still around. I'm not thinking this is worth fixing since I'm not sure I've ever seen a fuzz error show up on CTQ in the history of it's life, and it would probably be a lot of work.

```
CTQ additional failure:
simFuzz: Error: Error: Error: Assertion failed: Screen tandems should end with Screen suffix
    at window.assertions.assertFunction (http://localhost:59717/assert/js/assert.js:28:13)
    at new Screen (http://localhost:59717/chipper/dist/js/joist/js/Screen.js:120:17)
    at new LabScreen (http://localhost:59717/chipper/dist/js/natural-selection/js/lab/LabScreen.js:39:5)
    at http://localhost:59717/chipper/dist/js/natural-selection/js/natural-selection-main.js:17:78
    at Namespace.window.phet.joist.launchSimulation (http://localhost:59717/chipper/dist/js/joist/js/simLauncher.js:62:9)
    at http://localhost:59717/chipper/dist/js/joist/js/simLauncher.js:80:27
    at http://localhost:59717/chipper/dist/js/phet-core/js/asyncLoader.js:38:42
    at Array.forEach (<anonymous>)
    at AsyncLoader.proceedIfReady (http://localhost:59717/chipper/dist/js/phet-core/js/asyncLoader.js:38:22)
    at Image.<anonymous> (http://localhost:59717/chipper/dist/js/phet-core/js/asyncLoader.js:51:12)
3 pre-existing errors remain.

[4:28](https://phetsims.slack.com/archives/C03G9D6NY07/p1682634486002929)
CTQ additional failure:
simFuzz: Error: Error: Error: Assertion failed: Screen tandems should end with Screen suffix
    at window.assertions.assertFunction (http://localhost:59733/assert/js/assert.js:28:13)
    at new Screen (http://localhost:59733/chipper/dist/js/joist/js/Screen.js:120:17)
    at new LabScreen (http://localhost:59733/chipper/dist/js/natural-selection/js/lab/LabScreen.js:39:5)
    at http://localhost:59733/chipper/dist/js/natural-selection/js/natural-selection-main.js:17:78
    at Namespace.window.phet.joist.launchSimulation (http://localhost:59733/chipper/dist/js/joist/js/simLauncher.js:62:9)
    at http://localhost:59733/chipper/dist/js/joist/js/simLauncher.js:80:27
    at http://localhost:59733/chipper/dist/js/phet-core/js/asyncLoader.js:38:42
    at Array.forEach (<anonymous>)
    at AsyncLoader.proceedIfReady (http://localhost:59733/chipper/dist/js/phet-core/js/asyncLoader.js:38:22)
    at Image.<anonymous> (http://localhost:59733/chipper/dist/js/phet-core/js/asyncLoader.js:51:12)
3 pre-existing errors remain.

[4:28](https://phetsims.slack.com/archives/C03G9D6NY07/p1682634505594419)
CTQ additional failure:
simFuzz: Error: Error: Error: Assertion failed: Screen tandems should end with Screen suffix
    at window.assertions.assertFunction (http://localhost:59750/assert/js/assert.js:28:13)
    at new Screen (http://localhost:59750/chipper/dist/js/joist/js/Screen.js:120:17)
    at new LabScreen (http://localhost:59750/chipper/dist/js/natural-selection/js/lab/LabScreen.js:39:5)
    at http://localhost:59750/chipper/dist/js/natural-selection/js/natural-selection-main.js:17:78
    at Namespace.window.phet.joist.launchSimulation (http://localhost:59750/chipper/dist/js/joist/js/simLauncher.js:62:9)
    at http://localhost:59750/chipper/dist/js/joist/js/simLauncher.js:80:27
    at http://localhost:59750/chipper/dist/js/phet-core/js/asyncLoader.js:38:42
    at Array.forEach (<anonymous>)
    at AsyncLoader.proceedIfReady (http://localhost:59750/chipper/dist/js/phet-core/js/asyncLoader.js:38:22)
    at Image.<anonymous> (http://localhost:59750/chipper/dist/js/phet-core/js/asyncLoader.js:51:12)
3 pre-existing errors remain.

```

Back to @zepumph if anything else to do before close.

**Comment by zepumph** [comment]
So still to investigate:

- [ ] lint.js should provide stderr when facing problems (likely from the composite structure of linting individual repos)
- [ ] Figure out how to make sure puppeteer fails to CTQ if you have a very upstream error like `throw new Error()` in main
- [ ] Update the "comparison" logic for fuzzing errors to ignore `/localhost:\d}` so that ports don't cause reporting to think there is a new error.

**Comment by zepumph** [comment]
> * [x]  Figure out how to make sure puppeteer fails to CTQ if you have a very upstream error like `throw new Error()` in main
> *

Yes I'm pretty sure you are right. I also encountered it only sometimes throwing an error because the sim fuzz is only for 1 second when testing.

**Comment by zepumph** [comment]
Alright. With a bit of a weird try catch in lint, we can force stderr from occurring. This means that problems with Line will be handled separately, upstream of trying to parse the lint errors (which would likely result in a false negative).

Everything else here has been handled. Thanks so much @chrisklus for the timely review.
