### ISSUE TITLE
npm used up all /tmp space?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/aqua#20]
Continuous testing was failing with:
```
1|continuo | 2017-05-05T16:23:28.018Z [ERROR] Failure to npm update /data/share/phet/continuous-testing//snapshot-1494001255097/area-builder:
1|continuo | npm ERR! Linux 3.10.0-514.2.2.el7.x86_64
1|continuo | npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "update" "--cache=../npm-caches/area-builder"
1|continuo | npm ERR! node v6.9.1
1|continuo | npm ERR! npm  v3.10.8
1|continuo | npm ERR! path /tmp/npm-80366-949b5586
1|continuo | npm ERR! code ENOSPC
1|continuo | npm ERR! errno -28
1|continuo | npm ERR! syscall mkdir
1|continuo | npm ERR! nospc ENOSPC: no space left on device, mkdir '/tmp/npm-80366-949b5586'
1|continuo | npm ERR! nospc This is most likely not a problem with npm itself
1|continuo | npm ERR! nospc and is related to insufficient space on your system.
1|continuo | npm ERR! Please include the following file with any support request:
1|continuo | npm ERR!     /data/share/phet/continuous-testing/snapshot-1494001255097/area-builder/npm-debug.log
```

It's created ~230MB of temporary files.

I'm looking into having npm use a separate temporary directory (that we'll delete anyways).

@markmorlino, I didn't see anything mounted to /tmp directly, is there any way we can avoid this in the future?

**Comment by jonathanolson** [comment]
https://github.com/npm/npm/issues/6761 looks related.

**Comment by markmorlino** [comment]
I think by default on RH7 /tmp is using tmpfs so it is mapped to ram and swap. We can mount a disk partition to /tmp instead but that may have other side effects for other things using /tmp. I think pointing npm at a different directory is probably the best way to go. We can setup a separate mountpoint for that if you want to limit how big it can get or we can use a folder under /home or /data since it doesn't seem like it needs that much space and it sounds like you already have something in mind to be able to keep it from storing old temp files forever.

**Comment by jonathanolson** [comment]
> I think pointing npm at a different directory is probably the best way to go.

Thanks for the quick reply! A limit sounds much more complicated, and I have a working solution (--cache=DIR seems to work for npm).
