### ISSUE TITLE
CT not finishing tests 11/12/24

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/aqua#222]
CT is not finishing tests, even when it should have plenty of time to, such as overnight. While tests look green, only a small fraction seem to complete, and the completed amount seems fairly consistent.
![notdone1](https://github.com/user-attachments/assets/bb396063-3492-4f2a-b26e-acd6783cd582)
![notdone2](https://github.com/user-attachments/assets/455de97c-2d95-4ba6-b687-3eb9c97c3ab6)

**Comment by zepumph** [comment]
Looks like there was something that could happen to Puppeteer such that it would crash and never return back to the node process. Here is the log:

```
2024-11-09T12:41:09: info: [CONSOLE] enabling assert
2024-11-09T12:41:09: info: [LOADED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1731176137683%2Fnumber-play%2Fnumber-play_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26locales%3D*%26secondLocale%3Des&testInfo=%7B%22test%22%3A%5B%22number-play%22%2C%22second-language-fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1731176137683%22%2C%22timestamp%22%3A1731181265067%7D
2024-11-09T12:41:12: info: [CONSOLE] continuous-test-load
2024-11-09T14:16:23: info: [ERROR] Error: Page crashed!
```


This shows one instance going out of commission. I could track down that over the course of the last week, we lost every single one of our 100 instances this way. 

I'm unsure why we are encountering this, and the generic page crash error is generally unhelpful when googling. I added a timeout so that we can continue in the process when this happens. I believe tolerance is our number one desire, and then trying to fix the underlying issue should come next.

**Comment by zepumph** [comment]
The error could be a result of changes I have made in the code, but nothing looked very scary. I stared at this one for a long time: https://github.com/phetsims/perennial/commit/f6a0b7a4a62383470b797d0391f0450b78aa6b94 with no leads.


I also wondered if it had to do with me installing puppeteer 23 locally on the server one night just briefly before reverting the change, but that wouldn't explain the same issue in Bayes. 

I also wonder if it is because of a particularly unique kind of error that a sim was triggering which puppeteer has a bug in. This seems unlikely, but will be worth remembering if future issues are entirely based around number-pairs, but this is a bit hard to track down since I combined logs for all chrome processes.

**Comment by zepumph** [comment]
I think 20 minutes was too fast. Really we just want to handle the most catastrophic errors, so a couple hours seems fine to me.

**Comment by zepumph** [comment]
I don't believe we will see this again. Closing

**Comment by zepumph** [comment]
Still having some trouble. This time about space.

**Comment by zepumph** [comment]
`ct-main/` is taking up `950GB` of our 1000GB on /data. Let's remove old snapshots.

**Comment by zepumph** [comment]
We ran `git gc` in binder/ in `ct-main` and `ct-quick` and found that binder went from 13GB to 900MB. Closing
