### ISSUE TITLE
Is bayes no longer running unit tests?

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#36]
I noticed that http://localhost/axon/axon-tests.html fails with `Uncaught ReferenceError: PhetioIDUtils is not defined`.  I will need to regenerate the unit test HTMLs but I'm wondering why Bayes didn't catch this kind of issue.  Is it no longer running unit tests?

**Comment by samreid** [comment]
It seems Bayes was running the unit tests, but how were they not failing until they got the updates committed above?  I'm confused.

**Comment by jonathanolson** [comment]
Tested Scenery unit tests, and it looks like it was stalling out trying to request an image from a relative path (example-image-1.png). Since the test HTML moved to the top level, the relative path was incorrect (but would actually "work" if localhost://scenery pointed to scenery, since the extra `../` would be ignored). This looks like it stalled out that one test, and prevented test completion (which ideally should be an error in its own right).

Will check back in a bit to see if Scenery unit tests now complete (@phet-steele FYI).

**Comment by pixelzoom** [comment]
@ariel-phet can this be closed?   The last comment was on 1/3/2018, when @jonathanolson said he would "check back in a bit".

**Comment by jonathanolson** [comment]
Unit tests completing!
