### ISSUE TITLE
[continuous testing] add browser/device identification

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/aqua#43]
Probably needed for https://github.com/phetsims/QA/issues/120.

Undecided yet as to whether recording the user-agent would be sufficient. One way would be to set a stored configuration "name" in each browser used for testing that would be used for reporting, e.g. `bayes-chrome` (or generally the name of the device, and the name of the browser) so that we could track down the exact device needed for reproduction.

Would probably be good to discuss sometime with @lmulhall-phet and @ariel-phet to decide on what would be best.

**Comment by lmulhall-phet** [comment]
@jonathanolson @ariel-phet what's going on with this issue?

**Comment by ariel-phet** [comment]
It seems like IE was the main culprit in the past that would have been good to test. Currently this request has not really come up much, and CT has been catching the bulk of errors. If we run into another platform that seems worthy we can revisit, but closing this one, especially since the parent issue has been closed.
