### ISSUE TITLE
Node should serve files directly to puppeteer

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#97]
From #90 

> Having a hardcoded slash after the localTestingURL was causing bugs for me on Windows http-server, and this was not how we used localTestingURL when generating PhET-iO API files. I removed that hard coded slash, and added support for dynamically adding it if it isn't provided from the client's build-local.

Another way to address this would be to have node serve the files to puppeteer instead of relying on the developer localhost.  We implemented this for https://github.com/phetsims/phet-io/issues/1664 and the same should be possible here.

**Comment by samreid** [comment]
Let's try to factor out common code between this and https://github.com/phetsims/chipper/commit/9d74fe9631d73521029ff548d13549813991975e

**Comment by samreid** [comment]
The usages of `localTestingURL` in aqua/Gruntfile.js fall more under the CT umbrella, and I can't tell whether it would be appropriate to use `http.createServer` in those cases.  @jonathanolson what do you recommend?

**Comment by samreid** [comment]
The other part for aqua is in https://github.com/phetsims/aqua/blob/0cf643eb817a2c2ec594183ca37bcf6b069b3bac/js/local/puppeteerQUnit.js#L85

**Comment by zepumph** [comment]
In https://github.com/phetsims/perennial/issues/175#issuecomment-878409712 I was surprised that I found that when using http.createServer to load a sim in binder, a bug in supplying the MIME type (Content-Type header) broke the sim. Why does this not occur with the Continuous Server? perhaps because I was specifying an svg incorrectly as a `plain/text`. Do you think this server could benefit from using `withServer`? Or does it need to exist longer than that function is set up to?

**Comment by zepumph** [comment]
In regards to https://github.com/phetsims/aqua/issues/97#issuecomment-657103988, this no longer uses localTestingURL because of its usage change over in https://github.com/phetsims/aqua/issues/97#issuecomment-657103988 in hook-pre-commit to use withServer, so I think this is really just about ContinuousServer.js

**Comment by jonathanolson** [comment]
> The usages of localTestingURL in aqua/Gruntfile.js fall more under the CT umbrella, and I can't tell whether it would be appropriate to use http.createServer in those cases. @jonathanolson what do you recommend?

Seems possible to serve that way, but would it be a performance hit? Seems nice to factor it out so it's not needed if possible.

**Comment by samreid** [comment]
I'm not very familiar with it, but it seems that `ContinuousServer` is supposed to last longer than the `withServer` is designed for.  @zepumph what do you recommend?

**Comment by zepumph** [comment]
ContinuousServer.startServer begins and runs until the program stops. Sounds like we should leave it as is. I think this issue is outdated and should be closed.

**Comment by samreid** [comment]
Closing sounds good to me.

**Comment by zepumph** [comment]
I also want to add that we now have a puppeteer-based client for CT, see #143
